### ISSUE TITLE
使用PDO方式连接报异常,普通方式没问题

### ISSUE THREAD

**Issue by cqllang** [twang2218/docker-lnmp#1]
使用以下测试文件连接成功:
`<?php
$conn = mysqli_connect("mysql", "root", $_ENV["MYSQL_PASSWORD"]);
if (mysqli_connect_errno()) {
    die("连接错误: (" . mysqli_connect_errno() . ") " . mysqli_connect_error());
}
mysqli_close($conn);
?>
`

但用另一个测试文件：
`<?php
   try {            
           new PDO("mysql:host=127.0.0.1;dbname=mysql;port=3306",'root','xxx');
            echo "success";
        } catch (Exception $e) {
           echo "failed:" . $e;           
        }
?>
`
报异常::
`failed:PDOException: SQLSTATE[HY000] [2002] Connection refused in /usr/share/nginx/html/index.php:4 Stack trace: #0 /usr/share/nginx/html/index.php(4): PDO->__construct('mysql:host=127....', 'root', 'xxx') #1 {main}`

直接用xampp没问题？
是不支持pdo的连接么？

有什么建议可以给我么？

**Comment by rexleimo** [comment]
我觉是没有 pdo 扩展

**Comment by khs1994** [comment]
不能用 127.0.0.1 ，把各容器想象为独立的电脑，你就知道为什么了！！！

**Comment by khs1994** [comment]
```
<?php 
try { 
new PDO("mysql:host=mysql;dbname=mysql;port=3306",'root','xxx'); echo "success"; 
} 
catch (Exception $e) { 
echo "failed:" . $e; 
} 
```

**Comment by cqllang** [comment]
OK 解决了!
Thx!

**Comment by khs1994** [comment]
一个容器一个服务，一般情况下不能使用 127.0.0.1 等本地 ip 地址
